services:
  server:
    build:
      context: /Users/viana/Documents/GitHub/bia
    container_name: bia
    environment:
      DB_HOST: database
      DB_PORT: "5432"
      DB_PWD: postgres
      DB_USER: postgres
    ports:
      - mode: ingress
        target: 8080
        published: "80"
        protocol: tcp
